<?php

namespace App\Core\Enum;

enum ServerLogActionEnum
{
   case CHANGE_DETAILS;
   case REINSTALL;
   case CHANGE_STARTUP_OPTION;
   case CHANGE_STARTUP_VARIABLE;
   case TOGGLE_AUTO_RENEWAL;
   case CREATE_BACKUP;
   case DELETE_BACKUP;
   case DOWNLOAD_BACKUP;
   case RESTORE_BACKUP;
   case CREATE_DATABASE;
   case DELETE_DATABASE;
   case ROTATE_DATABASE_PASSWORD;
   case DELETE_ALLOCATION;
   case EDIT_ALLOCATION;
   case MAKE_PRIMARY_ALLOCATION;
   case CREATE_ALLOCATION;
   case CREATE_SUBUSER;
   case UPDATE_SUBUSER;
   case DELETE_SUBUSER;
   case ACCEPT_EULA;
   case CREATE_SCHEDULE;
   case UPDATE_SCHEDULE;
   case DELETE_SCHEDULE;
   case UPDATE_SCHEDULE_TASK;
   case CREATE_SCHEDULE_TASK;
   case DELETE_SCHEDULE_TASK;
}
