# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Exclude events from autowiring - they are created manually, not by DI container
    App\Core\Event\:
        resource: '../src/Core/Event/*'
        autowire: false
        autoconfigure: false

    # Dashboard Widget Registry
    App\Core\Service\Widget\DashboardWidgetRegistry:
        public: true

    # Auto-register builtin widgets as services
    App\Core\Widget\Dashboard\:
        resource: '../src/Core/Widget/Dashboard/*Widget.php'
        tags: ['dashboard.widget']
        autowire: true
        autoconfigure: true
