# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Exclude events from autowiring - they are created manually, not by DI container
    App\Core\Event\:
        resource: '../src/Core/Event/*'
        autowire: false
        autoconfigure: false

    # Dashboard Widget Registry
    App\Core\Service\Widget\DashboardWidgetRegistry:
        public: true

    # Auto-register builtin widgets as services
    App\Core\Widget\Dashboard\:
        resource: '../src/Core/Widget/Dashboard/*Widget.php'
        tags: ['dashboard.widget']
        autowire: true
        autoconfigure: true

    # Payment Gateway Manager
    App\Core\Service\Payment\PaymentGatewayManager:
        arguments:
            $providers: !tagged_iterator payment.provider

    # Auto-register payment providers as tagged services
    App\Core\Provider\Payment\:
        resource: '../src/Core/Provider/Payment/*Provider.php'
        tags: ['payment.provider']
        autowire: true
        autoconfigure: true

    # Server Tab Registry
    App\Core\Service\Tab\ServerTabRegistry:
        arguments:
            $tabs: !tagged_iterator server.tab

    # Auto-register builtin server tabs as tagged services
    App\Core\Tab\Server\:
        resource: '../src/Core/Tab/Server/*Tab.php'
        tags: ['server.tab']
        autowire: true
        autoconfigure: true
